---
name: CGI-Session-Driver-layered
version: 0.7
author:
  - 'Chris Reinhardt <creinhardt@liquidweb.com>'
abstract: Use multiple layered drivers
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  CGI::Session: 4
  Time::HiRes: 0
configure_requires:
  Module::Build: 0.34
provides:
  CGI::Session::Driver::layered:
    file: lib/CGI/Session/Driver/layered.pm
    version: 0.7
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
